// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT-9mIx6P-lr9brgwDWopfXG8NHHibMkY',
    appId: '1:274124008516:web:10c6c3c285c0601c6f2011',
    messagingSenderId: '274124008516',
    projectId: 'test-firebase-6bbbd',
    authDomain: 'test-firebase-6bbbd.firebaseapp.com',
    storageBucket: 'test-firebase-6bbbd.appspot.com',
    measurementId: 'G-54QFENZ78G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJRSuoIgrCc7tr4exCM7ElHh1zIuAcMo',
    appId: '1:274124008516:android:182e0dab1f54a72d6f2011',
    messagingSenderId: '274124008516',
    projectId: 'test-firebase-6bbbd',
    storageBucket: 'test-firebase-6bbbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApRQcXsGC9aT5Uq1xiJ-EWpbcp_UGxIOo',
    appId: '1:274124008516:ios:6c0e02668249de0a6f2011',
    messagingSenderId: '274124008516',
    projectId: 'test-firebase-6bbbd',
    storageBucket: 'test-firebase-6bbbd.appspot.com',
    iosBundleId: 'com.example.deshiMartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApRQcXsGC9aT5Uq1xiJ-EWpbcp_UGxIOo',
    appId: '1:274124008516:ios:6c0e02668249de0a6f2011',
    messagingSenderId: '274124008516',
    projectId: 'test-firebase-6bbbd',
    storageBucket: 'test-firebase-6bbbd.appspot.com',
    iosBundleId: 'com.example.deshiMartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT-9mIx6P-lr9brgwDWopfXG8NHHibMkY',
    appId: '1:274124008516:web:ad1385c0e2386f846f2011',
    messagingSenderId: '274124008516',
    projectId: 'test-firebase-6bbbd',
    authDomain: 'test-firebase-6bbbd.firebaseapp.com',
    storageBucket: 'test-firebase-6bbbd.appspot.com',
    measurementId: 'G-PJ0PGGW9DZ',
  );
}
